openapi: 3.0.3
info:
  title: Dataset API
  description: This API provides a way to get, create, update, and delete datasets.
  version: 1.0.0

components:
  parameters:
    UsernameParam:
      name: username
      in: path
      required: true
      schema:
        type: string
    DatasetSlugParam:
      name: datasetSlug
      in: path
      required: true
      schema:
        type: string

  schemas:
    DatasetResponse:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
        name:
          type: string
        slug:
          type: string
        source:
          type: string
        description:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        user:
          type: object
          properties:
            image:
              type: string
            slug:
              type: string
    DatasetsResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        slug:
          type: string
        image:
          type: string

paths:
  /datasets/{username}:
    get:
      summary: Get datasets by user
      description: Get all datasets by username.
      operationId: GetDataset
      parameters:
        - $ref: "#/components/parameters/UsernameParam"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DatasetsResponse"
        400:
          description: Bad Request
        404:
          description: Not Found
  /datasets/{username}/{datasetSlug}:
    get:
      summary: Get a dataset
      description: Get a dataset by its username and dataset slug.
      operationId: GetDataset
      parameters:
        - $ref: "#/components/parameters/UsernameParam"
        - $ref: "#/components/parameters/DatasetSlugParam"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DatasetResponse"
        400:
          description: Bad Request
        404:
          description: Not Found
    put:
      summary: Sync a dataset
      description: Sync a dataset with its source.
      operationId: SyncDataset
      parameters:
        - $ref: "#/components/parameters/UsernameParam"
        - $ref: "#/components/parameters/DatasetSlugParam"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DatasetResponse"
        400:
          description: Bad Request
        404:
          description: Not Found
  /datasets/{username}/{datasetSlug}/zip:
    get:
      summary: Download a dataset zip
      description: Download a dataset zip by its username and dataset slug.
      operationId: DownloadDatasetZip
      parameters:
        - $ref: "#/components/parameters/UsernameParam"
        - $ref: "#/components/parameters/DatasetSlugParam"
      responses:
        200:
          description: OK
          content:
            application/zip:
              schema:
                type: string
                format: binary
        400:
          description: Bad Request
        404:
          description: Not Found
